### ISSUE TITLE
Function request on av.R

### ISSUE THREAD

**Issue by shbrief** [Bioconductor/AnVIL#21]
I'm trying to use AnVIL package in my notebooks, and would like to export data model table to Terra from R. Can we add this function? I see the function in the other direction, `AnVIL::avtable()`.

**Comment by mtmorgan** [comment]
Hi @shbrief can you be a bit more specific? Do you actually want to create a table of entities, the way you would by clicking on the '+' icon of the DATA panel of a workspace?

**Comment by bjstubbs** [comment]
If you have a dataframe with the data you want to upload to the dom, you can use httr to do it. The api doesn't work at the moment because rapiclient doesn't support csv uploads.

#upload new entity
uploadtsv<-function(workspaceNamespace,workspace,tsvFile){
    cmd='gcloud auth application-default print-access-token'
    bearer=system(cmd,intern=TRUE)
    url=paste0("https://api.firecloud.org/api/workspaces/",workspaceNamespace,"/",workspace,"/flexibleImportEntities")
    httr::POST(url=url,
               body=list(entities=httr::upload_file(tsvFile)),
               httr::add_headers(Authorization=paste("Bearer",bearer)),
               encode="multipart")    
}

uploadEntities<-function(workspaceNamespace,workspace,entDF,entName){
    names(entDF)[1]=paste0("entity:",entName,"_id")
    entDF=entDF[,-2]
    tempfile=tempfile(fileext = ".tsv")
    write.table(entDF,file=tempfile,quote=FALSE,row.names=FALSE,sep="\t")
    uploadtsv(workspaceNamespace,workspace,tempfile)    
}
uploadEntities("mybilling","BioconductorLungGTEx",femaleSubjects,"femaleSubjects")
Response [https://api.firecloud.org/api/workspaces/landmarkanvil2/BioconductorLungGTEx/flexibleImportEntities]
  Date: 2019-08-28 17:37
  Status: 200
  Content-Type: application/json; charset=UTF-8
  Size: 14 B

**Comment by bjstubbs** [comment]
I am not sure how to do sample sets at the moment

**Comment by shbrief** [comment]
@mtmorgan Yes, that's what I'm looking for.
@bjstubbs Thanks, BJ! These functions are very helpful - I can use these for now. :)

**Comment by mtmorgan** [comment]
This needs the most recent AnVIL_rapiclient, install with `BiocManager::install("Bioconductor/AnVIL_rapiclient")`

Also, I'm not sure how often one wants to make a 'table', I think these are more meant as properties of the workspace derived from public data resources. For instance, there is no way that I see to _delete_ a table once it's been created...

**Comment by shbrief** [comment]
About the use cases, I agree it's less likely to update 'participant' and 'sample' entity tables, especially if you inherit them from the existing workspace with public data. But I expect to modify 'participant_set' and 'sample_set' entity tables fairly often - set entities seem to be the most convenient way to subset data. (FYI, my previous trouble shooting on this: https://support.terra.bio/hc/en-us/community/posts/360043301312-Efficient-way-to-Select-samples-to-process-in-Terra-)
