### ISSUE TITLE
Token expiration error

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/AnVIL#45]
Hi Martin, @mtmorgan 

Here is the diagnostic text when the token expiration erorr occurs:
```r
> samples <- avtable("sample")
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head><script src="https://us.jsagent.tcell.insight.rapid7.com/tcellagent.min.js" tcellappid="FCProd-EBOgM" tcellapikey="AQQBBAFLGLOxL7VE9IF9ESlLvCxD5Ykr_7xkQKq_rgn_P58IWjOhOzIh6p3aI4pTWaprlUw" tcellbaseurl="https://us.agent.tcell.insight.rapid7.com/api/v1"></script>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
<hr>
<address>Apache Server at api.firecloud.org Port 443</address>
</body></html>
Error: 'avtable' failed:
  Unauthorized (HTTP 401).
```

It seems to happen after 30 minutes... :thinking:

**Comment by mtmorgan** [comment]
Thanks! I set the token to expire 60 minutes after I first request it based on [stackoverflow wisdom](https://stackoverflow.com/a/50372687/547331); Jiefei has it expire after 50 minutes (I guess because 60 minutes didn't work?).

Following the second response on StackOverflow, I eventually got to [gcloud documentation](https://cloud.google.com/sdk/gcloud/reference/auth/application-default/print-access-token) and
```
jupyter@c8f5c841371d:~$ curl -H "Content-Type: application/x-www-form-urlencoded" -d "access_token=$(gcloud auth application-default print-access-token)" https://www.googleapis.com/oauth2/v1/tokeninfo
{
  ...
  "expires_in": 2451,
  ...
}
```
which was 60 minutes, but after the runtime started (or started to start...), rather than when I first requested the access token.

I'll update the AnVIL package and post here when ready...

**Comment by LiNk-NY** [comment]
Perhaps there is some overlap between Jiefei's suggestion and https://github.com/Bioconductor/AnVIL/pull/25/files ?

**Comment by Jiefei-Wang** [comment]
> Thanks! I set the token to expire 60 minutes after I first request it based on [stackoverflow wisdom](https://stackoverflow.com/a/50372687/547331); Jiefei has it expire after 50 minutes (I guess because 60 minutes didn't work?).

I've forgotten exactly why I set it to 50mins, but yes I think this at least leaves some room for error. It's better to be conservative here because the cost of token refresh is trivial.

**Comment by mtmorgan** [comment]
Actually what happens (at least in the command line) at the 50-minute mark is that the token isn't expired, and when you re-request it you get the same token; you'll hold it for another 50 minutes, the last 40 of which it *will* be expired... I guess the algorithm is designed to minimize the number of tokens generated, and the number of valid tokens associated with the account.

**Comment by mtmorgan** [comment]
I'll re-insert my memory of the comment I just deleted -- at least in AnVIL for a service account, re-requesting a token only generates it if it is expired
```
rstudio@b3ab86290867:~$ date; gcloud auth print-access-token
Wed 12 Jan 2022 10:52:27 PM UTC
<a token>
rstudio@b3ab86290867:~$ date; gcloud auth application-default print-access-token
Wed 12 Jan 2022 10:53:14 PM UTC
<same token>
```
So caching it for less than the expiry time (e.g., 50 rather than 60 minutes) means that the 'new' cached token is actual the same as the original, and will be expired for, e.g., the last 40 minutes of its time in the cache.

My plan is to get and record the expiry time, cache for a few seconds less than the expiry time (to allow for latency) then get and record the 'new' token. Worst case is that I make a couple of unnecessary calls to generate / cache the token, but this is ok for my purposes...
