### ISSUE TITLE
Errors retrieving information for Open Access DRS URIs

### ISSUE THREAD

**Issue by RobertJCarroll** [Bioconductor/AnVIL#59]
I'm trying to use DRS for the first time, but I think I may have run into an issue. I am attempting to retrieve information for an Open Access file. With the RStudio 3.15.1 image running in Terra, I am doing the following:
`library(AnVIL)
drs_stat("drs://data.kidsfirstdrc.org/cab44231-a03d-4d8e-9872-6ecd5e62ba6e")`
I get the following error:

> Error: 'DRS resolution' failed:
  Internal Server Error (HTTP 500).
  Received error contacting DRS provider. Fence access token required for https://data.kidsfirstdrc.org/ga4gh/drs/v1/objects/cab44231-a03d-4d8e-9872-6ecd5e62ba6e/access/s3 but is missing. Does use have an account linked in Bond?

However, I can visit that URL with no issue from an incognito window, which reflects what I'd expect as it's open access.

On the scope of the function (which is perhaps a user error/expectations issue), I was hoping I could also use these tools to get information from a DRS service even if I don't have access to the file (which appears to be supported for controlled access files).

And with the error message: I don't know what Bond is, and I can't find any information about it in the documentation or searching around online.

Please let me know if I can provide more information or you have ideas that can help me.

**Comment by mtmorgan** [comment]
I see this also with that drs address. To debug, I tried to eliminate as much infrastructure as possible. I launched a jupyter notebook image, and then a console, and executed the command line
```
jupyter@4abb7c963e28:~$ tnu drs info drs://data.kidsfirstdrc.org/cab44231-a03d-4d8e-9872-6ecd5e62ba6e
2022-06-21 12:14:31::WARNING  b'{"status":500,"response":{"status":500,"text":"Received error contacting DRS provider. Fence access token required for https://data.kidsfirstdrc.org/ga4gh/drs/v1/objects/cab44231-a03d-4d8e-9872-6ecd5e62ba6e/access/s3 but is missing. Does use have an account linked in Bond?"}}'
DRSResolutionError: Unexpected response while resolving DRS URI. Expected status 200, got 500. Received error contacting DRS provider. Fence access token required for https://data.kidsfirstdrc.org/ga4gh/drs/v1/objects/cab44231-a03d-4d8e-9872-6ecd5e62ba6e/access/s3 but is missing. Does use have an account linked in Bond?
```

I too can follow the https:// link in this error message, and get a response. Note that in the response there is a reference to `user=anonymous`.

I think that DRS is trying to give you access as an authenticated user, rather than as 'anonymous'. IIn the Terra UI, I navigated `Hamburger -> <AnVIL user name> -> Profile -> Kids First DRC Framework Services -> Log in to Kids First DRC Framework Services`. For me I was prompted for NIH credentials then Gen3 access permissions. This seemed to be 'successful' (I don't know whether this is successful for everyone, or individuals who have authenticated Kids First access, or because I have access as a 'developer'...). The mapping between AnVIL user id and Kids First access is facilitated, I believe, by a service called 'Bond' (implemented at https://github.com/DataBiosphere/bond)

Now in python I get
```
jupyter@4abb7c963e28:~$ tnu drs info drs://data.kidsfirstdrc.org/cab44231-a03d-4d8e-9872-6ecd5e62ba6e
{
  "name": "3e44a2f3-22c7-4a72-bc7f-e5b7608b9026.rsem.genes.results.gz",
  "size": 2497093,
  "updated": "2022-05-10T16:59:41.822Z",
  "checksums": {
    "sha256": "a6af78fa6c97c5ad8e66bb7a0bb078c5e7f0eb289e3c5ad9d745c7cdeecf4a7b",
    "md5": "671e600221a834118661e0bee5001ec3"
  }
}
```

Unfortunately, back in R I now get
```{r}
> drs_stat("drs://data.kidsfirstdrc.org/cab44231-a03d-4d8e-9872-6ecd5e62ba6e")
Error in `full_join()`:
! Can't join on `x$accessUrl` x `y$accessUrl` because of incompatible
  types.
ℹ `x$accessUrl` is of type <list>>.
ℹ `y$accessUrl` is of type <character>>.
Run `rlang::last_error()` to see where the error occurred.
```
I have fixed this, and mentioned Bond in the help page.

You will need to install the updated package from github

```
BiocManager::install("Biocoonductor/AnVIL")
```

or wait for the Bioconductor build system's nightly build to complete (24-48 hours, I think...) and install from there
```
BiocManager::install("AnVIL")
```
I'm not 100% sure whether your use case is supported -- the Kids First DRS resolution returns an accessUrl, whereas other services do not (yet). For the other services, e.g., Gen3, it is the case that `drs_stat()` provides information even without credentials, but that doesn't seem to be the case for Kids First. I will look into this a bit more...

**Comment by RobertJCarroll** [comment]
Thanks, I appreciate the detailed rundown and notes!

Sounds like this error is actually from TNU's DRS resolution process, not from this package. I originally saw the documentation copy here: https://rdrr.io/github/Bioconductor/AnVIL/man/drs.html which suggested three functions, so I was hoping to get login free information. It looks like I'm running not into package problems, but limitations on the TNU.

Regarding the KF DRS service: it is Gen3 right now as well. I'm not sure re the different configurations here.

This user's perspective is that it would be nice to get DRS metadata that does not require auth without having to log in. IE, a `tnu drs info` or `AnVIL::drs_stat()` would return whatever I can get from the DRS service. Additionally/Alternatively, I could call a method / add a parameter that would enable me to get the signed access url if authN/authZ pan out. Right now I get a big html 401 error. It seems like it would be useful to just get an "unauthorized" flag in a normal return table- one could then further investigate or just ignore those files one cannot access.

For example, this controlled access file: `drs://data.kidsfirstdrc.org/72a4cd16-2cf0-4c45-b15a-c14352bc2ee7` can have it's metadata viewed: `https://data.kidsfirstdrc.org/ga4gh/drs/v1/objects/72a4cd16-2cf0-4c45-b15a-c14352bc2ee7/` . I was able to login (and get TNU CLI running on my RStudio image), and found that I can't get the DRS metadata for this file even after logging in. It DOES work now for the open access data, so thanks again for that information. 

Overall: Thank you for adding the extra help information. It looks like I need to take this request over to the TNU or Martha for more options.
