### ISSUE TITLE
`gsutil_cp` not copying files?

### ISSUE THREAD

**Issue by shbrief** [Bioconductor/AnVIL#60]
Hi Martin, 
I can't find the 'copied file' after running `gsutil_cp`. 
Any idea why this is happening?  
FYI, I tried both release and GitHub versions of AnVIL package. 

```
> list.files(dest_dir)
[1] "HSM7J4NY"                       "ibdmdb_test_visualizations.zip"
> gsutil_cp("gs://fc-5be6125d-4813-4931-8a25-38d02c5f50c2/4ac530ad-11cf-43b8-91a0-350bf91a2295/workflowMTX/46b55b08-a364-4320-9fad-5c6e245d1ab4/call-CountRelabECs/cacheCopy/humann_ecs_relab_counts.tsv", dest_dir, parallel = FALSE)
Copying gs://fc-5be6125d-4813-4931-8a25-38d02c5f50c2/4ac530ad-11cf-43b8-91a0-350bf91a2295/workflowMTX/46b55b08-a364-4320-9fad-5c6e245d1ab4/call-CountRelabECs/cacheCopy/humann_ecs_relab_counts.tsv...
/ [1 files][  107.0 B/  107.0 B]                                                
Operation completed over 1 objects/107.0 B.                                      
> list.files(dest_dir)
[1] "HSM7J4NY"                       "ibdmdb_test_visualizations.zip"
```

**Comment by mtmorgan** [comment]
Just guessing but is dest_dir a relative path?

**Comment by shbrief** [comment]
Ha! Yes, it works once I give an absolute file path. Why is this? `gsutil` itself seems to work with a relative file path...

**Comment by mtmorgan** [comment]
Can you tell me what `dest_dir` is? Does it contain a `~` or `.` or ...?

**Comment by shbrief** [comment]
The `dest_dir` was the relative file path including `~`. I just wonder why it worked for the `gsutil cp` command line function but not for the `gsutil_cp` R function. I can use an absolute path for `gsutil_cp`, btw.

**Comment by mtmorgan** [comment]
Thanks for the report -- the `gsutil_cp()` command previously took care to allow for spaces in local file names (using `shQuote()`), but this also meant that `~` and `.` and `..` were not expanded. Probably you have a directory called `~` in the current working directory (`getwd()`) of the R session you were running at the time. Be VERY VERY careful removing this directory, e.g., escape the special characters `rm \~/other_parts_of_path`, otherwise you will (attempt to) remove your entire home directory!!
