### ISSUE TITLE
Size limits on avtable_import?

### ISSUE THREAD

**Issue by smgogarten** [Bioconductor/AnVIL#76]
This might be an AnVIL issue and not an R package issue, but I'm having errors trying to import large tables with `avtable_import`. 

A description of the issue is [here](https://support.terra.bio/hc/en-us/community/posts/14227085087515-Size-limits-on-data-tables-) (no response from AnVIL support). I was never able to import the sample_set table successfully using `avtable_import_set`, instead I uploaded a series of TSV files from my local computer using the web interface to create my sets.

Now I'm trying a different table. The data I want to import is 600,000 rows and 152 columns. I set the batch size to be 5000 rows. The first 8 batches (40,000 rows) imported successfully, but on the 9th batch I again get the error

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
```

**Comment by mtmorgan** [comment]
I could try to make a `avtable_import_paged()` to import large tables chunk-wise; since the data is simulated, can it be shared, along with the precise commands you're currently using? Personally I think the curl problem is something subtle in the R / curl package, even though it is [blamed](https://github.com/jeroen/curl/issues/232#issuecomment-1160222277) on the 'server'. The other error reported in your support site post is definitely a server error, but perhaps the R/AnVIL code could be made more robust to that kind of problem.

**Comment by smgogarten** [comment]
I just shared a workspace with you that contains example files and an R notebook. I wasn't able to capture the error importing the large phenotype table that's the last code block in the notebook, as my AnVIL session timed out. Before that happened, the sample data table at least was appearing in the "Data" tab of the workspace, but now it's not displaying any tables and gives me a "failed to fetch" error when I refresh the page.

Update: after ~30 min and refreshing the page many times, the data tables do appear in the workspace, and all 600,000 rows of the phenotype table seem to have imported successfully (in batches of 5,000 rows each).

**Comment by smgogarten** [comment]
I tried to replicate the same code in a different workspace and got an error on the second batch:

```
phen_file <- "pheno_simulation_table.tsv"
phen <- read_tsv(phen_file)
n <- nrow(phen)
n_max <- 5000
blocks <- ((1:n) - 1) %/% n_max
for (i in unique(blocks)) {
  xtable <- phen[blocks == i,]
  avtable_import(xtable, entity="pheno_simulation_id")
}
```

```
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
Error: 'avtable_import' failed:
  Bad Gateway (HTTP 502).
```

**Comment by mtmorgan** [comment]
Just to say that I've tried to ask for clarification on the size limit and 502 server error from the Terra folks, without success yet; if there is not any movement in the next several days I'll try to implement an ad hoc paging system plus retry, but this might not be very satisfactory...

**Comment by mtmorgan** [comment]
As a partial update, the issue-76 branch (`BiocManager::install("Bioconductor/AnVIL", ref = "issue-76")`) implements your strategy of upload large tables in pages ('chunks'). It provides progress bar, and warns when a page fails. Currently one can then use `page=` and `pageSize=` to manually update the page. This is very clumsy and will be improved...

In speaking with the Terra people, it seems like the 502 Server Error occurs when there is an internal timeout on the server side (I think that sometimes there are other problems with large data, because the server error seems to occur quickly when data transfer to Terra is fast...). The timeout is because of the length of time required for the server to process large data. The only solution is to provide the large data in chunks that the server can manage in the available time. It is not apparent what an appropriate chunk size is; I've settled on about 200,000 elements (rows x columns), which seems to work most of the time. The current code can still fail when an upload spans the expiration of the 'token' used to authenticate; usually this is updated automatically but the existing code in the AnVIL package does not handle the long latency that these data imports seem to involve.

I'm not really sure how well supported these large tables are. For instance, I can't clone the workspace you created because it times out before the clone is complete. Also if I try to delete a large table it also times out (but seems to eventually complete, so this is quite confusing...). You've also mentioned that uploads would appear to fail (generate a 502) but actually succeed (I'd guess the data gets loaded to the server and the import process starts, then a timeout occurs and you are notified but the server continues the import process...).

I have been told that the size of the table to be concerned about is the `sum(dim(.data))`, i.e., row & column. I wonder if a better strategy is to minimize the data stored as entities (e.g., for workflow execution?) and to store the other data in a csv or database file on the workspace bucket?

For the later and especially the use of a database I have been really impressed with the speed of duckdb ([CRAN][]; [duckdb][]) for the type of static, column-oriented data represented by these tables. I downloaded your simulated data to a CSV file and put it into a duckdb database with code like

[CRAN]: https://cran.r-project.org/package=duckdb
[duckdb]: https://duckdb.org/docs/data/overview

```
## create local scratch space
dest_dir <- "~/tmp/issue-76"
if (!dir.exists(dest_dir))
    dir.create(dest_dir)
setwd(dest_dir)

## retrieve table to local .csv file
library(AnVIL)
avworkspace("primed-cc-scratch/test_large_data_tables")

pheno_simulation <- avtable_paged("pheno_simulation")
pheno_simulation_path <- file.path(dest_dir, "pheno_simulation.csv")
readr::write_csv(pheno_simulation, pheno_simulation_path)

## import into duckdb
library(duckdb); library(DBI)

duckdb_dir <- file.path(dest_dir, "issue_76.duckdb")
drv =  duckdb(duckdb_dir)
con = dbConnect(drv)
dbExecute(con, "INSTALL sqlite;")
dbExecute(con, "LOAD sqlite;")

sql <- paste0(
    ## SQL from https://duckdb.org/docs/guides/import/csv_import
    "CREATE TABLE pheno_simulation AS ",
    "SELECT * FROM read_csv_auto('", pheno_simulation_path, "');"
)
dbExecute(con, sql)
```

It can be stored to the bucket / restored to the disk with

```
## upload duckdb to bucket
avfiles_backup(duckdb_path)

## retrieve from bucket
restored_db_dir <- tempfile()
dir.create(restored_db_dir)
avfiles_restore("issue_76.duckdb", restored_db_dir)
restored_db <- file.path(restored_db_dir, "issue_76.duckdb")
```

and then used either with standard SQL commands or via dplyr, e.g.,

```
## SQL / DBI
library(duckdb)
duckdb_path <- "/Users/ma38727/tmp/issue-76/issue_76.duckdb"
con <- dbConnect(duckdb(duckdb_path))

## d(b)plyr
library(dplyr)
pheno_simulation <- tbl(con, "pheno_simulation")

## really fast, e.g
pheno_simulation |> count(pheno_8_rho_2_GA_1 > 0)
```

**Comment by smgogarten** [comment]
Thank you for this update! I tried out the new paged version of `avtable_import` and it worked well. I think something similar is needed for `avtable_import_set`, but it might be restricted by the smallest possible page being a single set.

**Comment by mtmorgan** [comment]
The next iteration of the code (still `avtable_import()` only) is available
```
BiocManager::install("Bioconductor/AnVIL", ref = "issue-76"))
```

As a small demo this adds the 'mtcars' dataset
```
mycars <-
  mtcars |>
  as_tibble(rownames = "model") |>
  mutate(model = gsub(" ", "_", model))
```
as a table, in chunks and as a two-step process.  The first step is to upload the data 'asynchronously'
```
> (job_status <- avtable_import(mycars, pageSize = 10))
pageSize = 10 rows (4 pages)
  |========================================================================| 100%
# A tibble: 4 × 3
   page job_id                               status        
  <int> <chr>                                <chr>         
1     1 30eafdb3-9f3b-4061-ad0a-51882cdc3c08 Uploaded     
2     2 8ebfe48f-d293-409b-89f4-fc56854ad342 Uploaded     
3     3 40cbb659-5619-4432-a218-471a72440935 Uploaded
4     4 4d26d829-dafa-45bb-af84-d1bbfd6eba74 Uploaded

```
The data is now on Terra, and terra is working in the background to insert chunks into the table. Check on the status of the jobs
```
> (job_status <- avtable_import_status(job_status))
checking status of 4 avtable import jobs
  |========================================================================| 100%
# A tibble: 4 × 3
   page job_id                               status        
  <int> <chr>                                <chr>         
1     1 30eafdb3-9f3b-4061-ad0a-51882cdc3c08 Upserting     
2     2 8ebfe48f-d293-409b-89f4-fc56854ad342 Upserting     
3     3 40cbb659-5619-4432-a218-471a72440935 ReadyForUpsert
4     4 4d26d829-dafa-45bb-af84-d1bbfd6eba74 ReadyForUpsert
```
save `job_status` to disk, go for coffee, etc, come back at some later point and check again
```
> (job_status <- avtable_import_status(job_status))
checking status of 4 avtable import jobs
  |========================================================================| 100%
# A tibble: 4 × 3
   page job_id                               status
  <int> <chr>                                <chr> 
1     1 30eafdb3-9f3b-4061-ad0a-51882cdc3c08 Done  
2     2 8ebfe48f-d293-409b-89f4-fc56854ad342 Done  
3     3 40cbb659-5619-4432-a218-471a72440935 Done  
4     4 4d26d829-dafa-45bb-af84-d1bbfd6eba74 Done  
```

If a page fails to upload, it has `job_id` `NA` and `status` `"Failed"`. I'll work on making it easier to retry failed uploads.

It seems to take 30-40s to upload each page for the larger data (there is some pre-processing going on, I guess, on the server side) so `avtable_import()` can still take a couple of tens of minutes when the R session is occupied. Actually inserting the data seems to take another 30-40s per page, but this is on the server so one can go about other business. I can't do anything about that.

Also, opening the workspace / navigating to the DATA tab can be slow and even fail the first time. It seems like one just 'tries again' to load the DATA tab until success. Again nothing I can do about that.
