### ISSUE TITLE
Error from `avtable` with an unconventional table name

### ISSUE THREAD

**Issue by shbrief** [Bioconductor/AnVIL#98]
Hi! I'm getting this error with this specific data table. Any suggestion how to fix this? Thanks!

```
> namespace = "pathogen-genomic-surveillance"
> name = "COVID-19"
> avdata <- avtables(namespace = namespace, name = name)
> res <- avtable(avdata$table[2], namespace = namespace, name = name)
Error: 'avtable()' failed, see 'Details' of `?avtable` for help
  URL rejected: Malformed input to a URL function
> avdata$table[2]
[1] "this is a test"
```

**Comment by mtmorgan** [comment]
I'm guessing that the spaces in the table name causes problems. Does 
```{r}
table_name = utils::URLencode(avdata$table[2])
avtable(table_name, namespace = namespace, name = name)
```
work?

**Comment by shbrief** [comment]
Humm... still not working. This is the error from the code you shared. 
```
> table_name = utils::URLencode(avdata$table[2])
> avtable(table_name, namespace = namespace, name = name)
Error: 'avtable' failed:
  Internal Server Error (HTTP 500).
  Illegal URI reference: Invalid input ' ', expected '/', 'EOI', '#', '?' or pchar (line 1, column 111): https://rawls.dsde-prod.broadinstitute.org/api/workspaces/pathogen-genomic-surveillance/COVID-19/entities/this is a test
```

**Comment by mtmorgan** [comment]
I'll leave this to @LiNk-NY to resolve, but what I've found out is

The AnVIL package uses the 'terra' API for this operation, specifically `Terra()$getEntities()` and https://api.firecloud.org/#/Entities/getEntities.

Using this swagger form, the terra API fails with entityType `this is a test`, like the AnVIL package.

Using the entityType `this%20is%20a%20test` succeeds on the swagger page, but the url seen in the curl command and sent to the service has incorrectly 'double-escaped' the string as `this%2520is%2520a%2520test`. I believe that (a) the unescaped entityType should works on this page and (b) the escaped entityType should also work, without double-escaping. These are issue for the Terra support desk.

The terra API actually forwards to RAWLS https://rawls.dsde-prod.broadinstitute.org/#/entities/list_entities. This endpoint works correctly for `this is a test`. It fails (I don't think it should) with `this%20is%20a%20test`.

A workaround in the AnVIL package would be to use `Rawls()$list_entities()` rather than `Terra()$getEntities()` and NOT encode the table name, but I thought (maybe incorrectly) that the Terra API was preferred to the RAWLS API.

**Comment by LiNk-NY** [comment]
Thanks Martin. 

It looks like the `entityType` (table name) is part of the URL so it has to be encoded: 

```
curl -X 'GET' \
  'https://rawls.dsde-prod.broadinstitute.org/api/workspaces/pathogen-genomic-surveillance/COVID-19/entities/this%20is%20a%20test' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer Token'
```

I believe part of the Terra API will be replaced by Rawls so forwarding requests makes sense. 

I was able to get a successful request by encoding the table name (`entityType`) and using `Rawls()$list_entities()`. 

I am actually working on a branch to transition from Terra requests to Rawls requests at https://github.com/Bioconductor/AnVIL/tree/terra_to_rawls 

I can add this fix to `devel` in the meantime.
